base:
  project : winequality-project
  random_state : 42
  target_col : TARGET

data_source:

  s3_source : data_given/winequality.csv

load_data:
  raw_data : data_given/winequalty.csv

split_data:
  train_data : data/processed/train_wine_quality.csv
  test_data : data/processed/test_wine_quality.csv
  test_size : 0.2